services:
  clasp:
    build:
      dockerfile_inline: |
        FROM node:20.11.1-bullseye-slim
        RUN apt-get update && \
            apt-get install -y curl && \
            npm -v && \
            npm i -g @google/clasp
        WORKDIR /app
        ENTRYPOINT [ "clasp" ]
    volumes:
      - login:/root
      - $PWD:/app
volumes:
  login:
    driver: local
